repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: detect-private-key

# Python specific hooks
-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
        language_version: python3

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.292'
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests, pydantic]
        exclude: ^(docs/|scripts/)

# Go specific hooks
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.54.2
    hooks:
    -   id: golangci-lint

# Rust specific hooks
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
    -   id: cargo-check
    -   id: clippy

# TypeScript/JavaScript specific hooks
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
    -   id: prettier
        types_or: [javascript, jsx, ts, tsx, json, css, markdown]

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.51.0
    hooks:
    -   id: eslint
        files: \.(js|ts|tsx)$
        types: [file]
        additional_dependencies:
        -   eslint@8.51.0
        -   eslint-config-prettier@9.0.0
        -   typescript@5.2.2
        -   @typescript-eslint/eslint-plugin@6.7.5
        -   @typescript-eslint/parser@6.7.5