version: '3.8'

# This docker-compose file is configured to work with Doppler for secrets management
# Always run with: doppler run -- docker-compose up -d
# This ensures all necessary environment variables are injected from Doppler

services:
  orchestrator:
    build:
      context: ./backend/orchestrator
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/orchestrator:/app
    environment:
      # These environment variables will be loaded from Doppler
      # Do not hardcode any values here
      - DATABASE_URL
      - KAFKA_BOOTSTRAP_SERVERS
      - JWT_SECRET
      - OPENAI_API_KEY
      - ANTHROPIC_API_KEY
      - HUGGINGFACE_API_KEY
      - LOG_LEVEL
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env # This will be populated by Doppler when running with doppler run
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - atheon-network

  scraper:
    build:
      context: ./backend/agents/scraper
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/agents/scraper:/app
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC_IN=scrape_requests
      - KAFKA_TOPIC_OUT=scrape_results
      - KAFKA_GROUP_ID=scraper_group
      - MAX_CONCURRENCY=10
      - USER_AGENT=Atheon-AI Web Scraper
      - LOG_LEVEL=info
    depends_on:
      kafka:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - atheon-network

  data_fetcher:
    build:
      context: ./backend/agents/data_fetcher
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./backend/agents/data_fetcher:/app
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC_IN=data_fetch_requests
      - KAFKA_TOPIC_OUT=data_fetch_results
      - KAFKA_GROUP_ID=data_fetcher_group
      - API_REQUEST_TIMEOUT=30
      - POLL_INTERVAL=1000
      - LOG_LEVEL=info
    depends_on:
      kafka:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - atheon-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      # Examples of environment variables that will be loaded via Doppler
      - NEXT_PUBLIC_API_URL
      - NODE_ENV
    env_file:
      - .env # This will be populated by Doppler when running with doppler run
    depends_on:
      orchestrator:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - atheon-network

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-atheon_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-atheon_password}
      - POSTGRES_DB=${POSTGRES_DB:-atheon}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-atheon_user} -d ${POSTGRES_DB:-atheon}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - atheon-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    networks:
      - atheon-network

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/bitnami/kafka
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server kafka:9092 --list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - atheon-network

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - atheon-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=atheon-kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      kafka:
        condition: service_started
    restart: unless-stopped
    networks:
      - atheon-network

volumes:
  postgres_data:
  kafka_data:
  redis_data:

networks:
  atheon-network:
    driver: bridge