---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  namespace: atheon-ai
spec:
  template:
    spec:
      containers:
      - name: orchestrator
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 3Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper
  namespace: atheon-ai
spec:
  template:
    spec:
      containers:
      - name: scraper
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-fetcher
  namespace: atheon-ai
spec:
  template:
    spec:
      containers:
      - name: data-fetcher
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi