apiVersion: v1
kind: Service
metadata:
  name: scraper
  labels:
    app: scraper
    component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8083"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: scraper
  ports:
  - name: http
    port: 80
    targetPort: 8082
    protocol: TCP
  - name: metrics
    port: 8083
    targetPort: 8083
    protocol: TCP
  type: ClusterIP