apiVersion: v1
kind: Secret
metadata:
  name: atheon-secrets
type: Opaque
stringData:
  # Database credentials
  postgres-user: "atheon_user"
  postgres-password: "${POSTGRES_PASSWORD}"
  database-url: "postgresql://atheon_user:${POSTGRES_PASSWORD}@postgres:5432/atheon"

  # JWT authentication
  jwt-secret: "${JWT_SECRET}"

  # LLM API keys
  openai-api-key: "${OPENAI_API_KEY}"
  anthropic-api-key: "${ANTHROPIC_API_KEY}"

  # Other secrets
  doppler-token: "${DOPPLER_TOKEN}"
---
apiVersion: v1
kind: Secret
metadata:
  name: github-registry
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "${GITHUB_USERNAME}",
          "password": "${GITHUB_TOKEN}",
          "email": "${GITHUB_EMAIL}",
          "auth": "${GITHUB_AUTH}"
        }
      }
    }