apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-fetcher
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: summarizer
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2