# In /infra/k8s/aws-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: <base64-encoded-access-key>
  AWS_SECRET_ACCESS_KEY: <base64-encoded-secret-key>
  AWS_S3_BUCKET: <base64-encoded-bucket-name>
  AWS_REGION: <base64-encoded-region>