---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  namespace: atheon-ai
spec:
  replicas: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper
  namespace: atheon-ai
spec:
  replicas: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-fetcher
  namespace: atheon-ai
spec:
  replicas: 1