---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  namespace: atheon-ai
spec:
  template:
    spec:
      containers:
      - name: orchestrator
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper
  namespace: atheon-ai
spec:
  template:
    spec:
      containers:
      - name: scraper
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-fetcher
  namespace: atheon-ai
spec:
  template:
    spec:
      containers:
      - name: data-fetcher
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi