apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - orchestrator-deployment.yaml
  - scraper-deployment.yaml
  - data-fetcher-deployment.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml
  - kafka-deployment.yaml