apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atheon-ai
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/atheon-ai/atheon-ai.git'
    targetRevision: main
    path: infra/kubernetes
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: atheon
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m