apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base directory
resources:
- ../../base

# Change the namespace for staging
namespace: atheon-ai-staging

# Set the namePrefix to avoid collisions with other environments
namePrefix: staging-

# Add environment-specific labels
commonLabels:
  environment: staging

# ConfigMap patches for staging environment
configMapGenerator:
- name: atheon-config
  behavior: merge
  literals:
  - ENVIRONMENT=staging
  - LOG_LEVEL=info

# Patches to customize resources for staging
patches:
- path: patches/replicas-patch.yaml
- path: patches/resources-patch.yaml

# Customize container images for staging
images:
- name: ${REGISTRY_URL}/atheon-ai/orchestrator
  newName: ${REGISTRY_URL}/atheon-ai/orchestrator
  newTag: ${STAGING_TAG}
- name: ${REGISTRY_URL}/atheon-ai/scraper
  newName: ${REGISTRY_URL}/atheon-ai/scraper
  newTag: ${STAGING_TAG}
- name: ${REGISTRY_URL}/atheon-ai/data-fetcher
  newName: ${REGISTRY_URL}/atheon-ai/data-fetcher
  newTag: ${STAGING_TAG}
- name: ${REGISTRY_URL}/atheon-ai/summarizer
  newName: ${REGISTRY_URL}/atheon-ai/summarizer
  newTag: ${STAGING_TAG}
- name: ${REGISTRY_URL}/atheon-ai/frontend
  newName: ${REGISTRY_URL}/atheon-ai/frontend
  newTag: ${STAGING_TAG}